runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /(.*\.css)
  static_files: dist/FrontEndT3/\1
  upload: dist/FrontEndT3/(.*\.css)
  
- url: /(.*\.html)
  static_files: dist/FrontEndT3/\1
  upload: dist/FrontEndT3/(.*\.html)

# Site root.
- url: /
  static_files: dist/FrontEndT3/index.html
  upload: dist/FrontEndT3/index.html

# Catch-all rule, responsible from handling Angular application routes (deeplinks).
- url: /.*
  static_files: dist/FrontEndT3/index.html
  upload: dist/FrontEndT3/index.html

